//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group2_iCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentMetadata
    {
        public string DocID { get; set; }
        public string DocName { get; set; }
        public Nullable<System.DateTime> DateOfCreation { get; set; }
    }
}
