//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group2_iCare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentMetadata
    {
        public string DocID { get; set; }
        public string DocName { get; set; }
        public Nullable<System.DateTime> DateOfCreation { get; set; }
        public string PatientID { get; set; }
        public string WorkerID { get; set; }
        public string ModifiedByID { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Descript { get; set; }
    
        public virtual iCAREUser iCAREUser { get; set; }
        public virtual PatientRecord PatientRecord { get; set; }
        public virtual iCAREWorker iCAREWorker { get; set; }
        public virtual ModificationHistory ModificationHistory { get; set; }
    }
}
